import Header from "@/components/header/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./style/style.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        data-theme={"dark"}
        className={`bg-gradient-to-r min-h-screen from-[#131a27] to-[#091324] text-white ${inter.className}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
